### ISSUE TITLE
Find the reference_id of a large scene previewed in the paper

### ISSUE THREAD

**Issue by glennliu** [WaldJohannaU/3RScan#11]
Hi Johanna

I intend to use a larger room scene from the dataset. One of them is the left third scene below, which I read from Fig. 18 of your paper,

![Screenshot from 2021-06-22 09-52-51](https://user-images.githubusercontent.com/8009679/122850554-ff9fdf80-d33f-11eb-8196-bc35bbcdee85.png)

Since I haven't found any method to preview the scene with reference id. Do you have any recommended method to find its corresponding reference_id?

Thanks

**Comment by WaldJohannaU** [comment]
Hi,

you can find a list of thumbnails of the scans here: https://campar.in.tum.de/files/3RScan/thumbnails.zip

The one from the figure:
fcf66db2-622d-291c-8493-4f2517282f3f

Some other scan-ids of larger rooms:
- 751a5598-fe61-2c3b-8cf2-1c23632af9b4
- 8eabc412-5af7-2f32-84dc-db30b0209267
- 74ef846e-9dce-2d66-83d5-294aac7b1b0f
- 280d8ebb-6cc6-2788-9153-98959a2da801
- 18d4d926-7eb5-280e-87df-199e66f2babd
- 751a559f-fe61-2c3b-8cec-258075450954
- e3004a81-9f2a-2778-874e-fa76b0e67096
- d7d40d60-7a5d-2b36-9573-5d5fe8bae949
- ba6fda9c-a4c1-2dca-8185-456923749a4e
- ad408c85-84db-2095-8af3-11fbabe6d684

Hope that helps!

**Comment by glennliu** [comment]
> Hi,
> 
> you can find a list of thumbnails of the scans here: https://campar.in.tum.de/files/3RScan/thumbnails.zip
> 
> The one from the figure:
> fcf66db2-622d-291c-8493-4f2517282f3f
> 
> Some other scan-ids of larger rooms:
> 
> * 751a5598-fe61-2c3b-8cf2-1c23632af9b4
> * 8eabc412-5af7-2f32-84dc-db30b0209267
> * 74ef846e-9dce-2d66-83d5-294aac7b1b0f
> * 280d8ebb-6cc6-2788-9153-98959a2da801
> * 18d4d926-7eb5-280e-87df-199e66f2babd
> * 751a559f-fe61-2c3b-8cec-258075450954
> * e3004a81-9f2a-2778-874e-fa76b0e67096
> * d7d40d60-7a5d-2b36-9573-5d5fe8bae949
> * ba6fda9c-a4c1-2dca-8185-456923749a4e
> * ad408c85-84db-2095-8af3-11fbabe6d684
> 
> Hope that helps!

Hi,

It seems the thumbnail link does not open to the public outside TUM. But the list your shared is helpful. I'll try with these scans. 

Thanks a lot!

**Comment by WaldJohannaU** [comment]
Sorry, the link was not correct, this one should work: http://campar.in.tum.de/files/3RScan/thumbnails.zip

**Comment by glennliu** [comment]
It works well. Thanks!
