### ISSUE TITLE
I cannot access the script downloading webpage...

### ISSUE THREAD

**Issue by timzsu** [WaldJohannaU/3RScan#14]
I filled in the form and was automatically directed to a webpage "3RScan: Request for Access", where I was given a link to download the script. However, when I click into the link, I received "404 Not Found" "nginx/1.18.0 (Ubuntu)" instead of the script. I have tried to access 3RScan.json and scans.txt by the corresponding link and got the same feedback. Using wget doesn't work as well. 
Is there anything wrong? Does anyone encounter the same problem with me? How can I get the download script?

**Comment by Masahiro1002** [comment]
I have the same problem...

**Comment by Lijin002** [comment]
I have encounterd the same problem. :(
If someone knows how to solve, could you please inform me?  Thx!

**Comment by Mr-Faceless** [comment]
I can't download the 3RScan dataset too.
If someone have the dataset ,could you please send me? Thanks a lot!

**Comment by glennliu** [comment]
I met the same problem recently. The link worked fine for me two months ago.

**Comment by Mr-Faceless** [comment]
> I met the same problem recently. The link worked fine for me two months ago.

Me too, and the dataset I downloaded was incomplete ,do you have complete  3RScan dataset?

**Comment by glennliu** [comment]
> > I met the same problem recently. The link worked fine for me two months ago.
> 
> Me too, and the dataset I downloaded was incomplete ,do you have complete 3RScan dataset?

I only downloaded several scans earlier. I can send it to you if you need it. 
Look like something is wrong with their website.

**Comment by Mr-Faceless** [comment]
> > > I met the same problem recently. The link worked fine for me two months ago.
> > 
> > 
> > Me too, and the dataset I downloaded was incomplete ,do you have complete 3RScan dataset?
> 
> I only downloaded several scans earlier. I can send it to you if you need it. Look like something is wrong with their website.

Please send it to 15005563803@163.com. Thanks a lot!

**Comment by Lijin002** [comment]
> > > I met the same problem recently. The link worked fine for me two months ago.
> > 
> > 
> > Me too, and the dataset I downloaded was incomplete ,do you have complete 3RScan dataset?
> 
> I only downloaded several scans earlier. I can send it to you if you need it. Look like something is wrong with their website.

Hi, could you please share the part of dataset with me? If it's ok, please send it to 2094796595@qq.com. Sincerely thank you!

**Comment by glennliu** [comment]
> > > > I met the same problem recently. The link worked fine for me two months ago.
> > > 
> > > 
> > > Me too, and the dataset I downloaded was incomplete ,do you have complete 3RScan dataset?
> > 
> > 
> > I only downloaded several scans earlier. I can send it to you if you need it. Look like something is wrong with their website.
> 
> Hi, could you please share the part of dataset with me? If it's ok, please send it to [2094796595@qq.com](mailto:2094796595@qq.com). Sincerely thank you!

ok, I send one scan to your email.
I also contact Johanna. She replied that they are upgrading their server. The latest link will be updated soon.

**Comment by ComaZzo** [comment]
> > > > > I met the same problem recently. The link worked fine for me two months ago.
> > > > 
> > > > 
> > > > Me too, and the dataset I downloaded was incomplete ,do you have complete 3RScan dataset?
> > > 
> > > 
> > > I only downloaded several scans earlier. I can send it to you if you need it. Look like something is wrong with their website.
> > 
> > 
> > Hi, could you please share the part of dataset with me? If it's ok, please send it to [2094796595@qq.com](mailto:2094796595@qq.com). Sincerely thank you!
> 
> ok, I send one scan to your email. I also contact Johanna. She replied that they are upgrading their server. The latest link will be updated soon.

Hello, could you send it to me too? Please send it to a14516566341@yandex.ru . Thank you very much!

**Comment by WaldJohannaU** [comment]
sorry for the late response. We had issues with our lab server and had to migrate all the datasets which took longer than expected. The new server with corresponding certificates is now finally ready to be used.

You should get the updated link if you edit/fill out the request form.

**Comment by 2WangZhen3** [comment]
> > > I met the same problem recently. The link worked fine for me two months ago.
> > 
> > 
> > Me too, and the dataset I downloaded was incomplete ,do you have complete 3RScan dataset?
> 
> I only downloaded several scans earlier. I can send it to you if you need it. Look like something is wrong with their website.

Please send it to 690469945@qq.com. Thanks a lot!

**Comment by xuxw98** [comment]
> sorry for the late response. We had issues with our lab server and had to migrate all the datasets which took longer than expected. The new server with corresponding certificates is now finally ready to be used.
> 
> You should get the updated link if you edit/fill out the request form.

Dear author, recently the download link seems to fail again. Is there anything wrong with the server?

**Comment by LongtermFcq** [comment]
> Hello, could you send it to me too? Please send it to [a14516566341@yandex.ru](mailto:a14516566341@yandex.ru) . Thank you very much!

Hello, could you send it to me too? Please send it to 19316344691@163.com . Thank you very much!

**Comment by LongtermFcq** [comment]
> > > > > I met the same problem recently. The link worked fine for me two months ago.
> > > > 
> > > > 
> > > > Me too, and the dataset I downloaded was incomplete ,do you have complete 3RScan dataset?
> > > 
> > > 
> > > I only downloaded several scans earlier. I can send it to you if you need it. Look like something is wrong with their website.
> > 
> > 
> > Hi, could you please share the part of dataset with me? If it's ok, please send it to [2094796595@qq.com](mailto:2094796595@qq.com). Sincerely thank you!
> 
> ok, I send one scan to your email. I also contact Johanna. She replied that they are upgrading their server. The latest link will be updated soon.

Hello, could you send it to me too? Please send it to [19316344691@163.com](mailto:19316344691@163.com) . Thank you very much!
