### ISSUE TITLE
Is your data from Scannet?

### ISSUE THREAD

**Issue by CurryYuan** [WaldJohannaU/3RScan#6]
I noticed that your scenes are very similar to Scannet. Is your data modified from Scannet or collected totally by yourself?

**Comment by WaldJohannaU** [comment]
Hi @CurryYuan,

the dataset was collected by ourself and doesn't have any overlap with ScanNet. We also use different sensors and algorithms for the acquisition, for more information please check out [our paper](https://arxiv.org/abs/1908.06109).

We however used the same annotation pipeline for the instance segmentation see [https://github.com/smartscenes/sstk/](https://github.com/smartscenes/sstk/) and therefore have a similar data formats.
