### ISSUE TITLE
How can I get the dataset?

### ISSUE THREAD

**Issue by WWWJL** [WaldJohannaU/3RScan#7]
Hi, i want to download your dataset, can you give me a link?

**Comment by WaldJohannaU** [comment]
Thank you for your interest in 3RScan. If you would like to download the data, please fill out [this form](https://forms.gle/NvL5dvB4tSFrHfQH6).

Afterwards you should get an email with download instructions.

**Comment by SunWeiLin-Lynne** [comment]
Hi，After running download.py, where is the dataset saved？
