### ISSUE TITLE
Inconsistent & unaligned annotations

### ISSUE THREAD

**Issue by czha5168** [WaldJohannaU/3RScan#8]
Hi Johanna,

Thanks for providing the dataset, which looks stunning. During my studies, I noticed some inconsistent annotated scenes, such as "20c993b9-698f-29c5-87f1-4514b70070c3". It seems the .obj files not only contain different #points than the .ply annotations files, but also miss almost half part of the scene. Moreover, these two files seem not aligned appropriately, producing a weird overlapping appearance. (Please see attached visualizations of .obj file, .ply file, and their overlapping below)

Could you please provide me with some suggestions on this kind of scenes? I am trying to obtain the 3D point cloud with corresponding vertex colour & vertex label (ObjId and CateId). Thanks!

**Comment by czha5168** [comment]
[
![anno](https://user-images.githubusercontent.com/40653168/89355328-74553580-d6fe-11ea-95a4-1fd8d76e4795.png)
![obj](https://user-images.githubusercontent.com/40653168/89355332-75866280-d6fe-11ea-8164-e8892b4ab5a3.png)
![overlap](https://user-images.githubusercontent.com/40653168/89355333-761ef900-d6fe-11ea-82d3-09539175c2d9.png)


](url)

**Comment by WaldJohannaU** [comment]
It looks like you are referring to a scan from our hidden test set, see [here](http://campar.in.tum.de/files/3RScan/test_rescans.txt). We didn't release the semantic segmentation of rescans in the hidden test set, but instead only provide the semantic annotations of the reference scan - they have different sizes and also changes, chair moved here e.g. Is it possible that you mixed up the file names or scan-ids?

The semantic segmentation and obj should always be aligned unless you are taking them from a different scan, how to align a rescan with it's reference scan is described in our [FAQ](https://github.com/WaldJohannaU/3RScan/blob/master/FAQ.md#how-to-align-the-rescan-3d-models-and-camera-poses-with-the-reference-scan).

Please let me know if you find a train or validation scan where labels and mesh are not aligned.

**Comment by czha5168** [comment]
Hi Johanna, Thanks for your quick reply. Now I understand that some preprocessing steps are required to align the testing scan (.obj file) to its reference scan (another .obj file). However, their corresponding annotations (.ply file) could not be transformed or generated from our side, even if the alignment step is completed, due to the changes between the testing scene and its reference one (e.g., moved chair). So would you have a plan on releasing the semantic segmentation annotations for us to complete an evaluation over these testing scans? Thanks.

P.S.: The website you mentioned (http://campar.in.tum.de/files/3RScan/test_rescans.txt) seems not accessible. Updated: Thanks for fixing the link!

**Comment by WaldJohannaU** [comment]
For train and validation scans there is an annotation `*.ply` file for each reference and rescan; I recommend to use these. We also provide poses for the objects that changed. See function `TransformInstance` in our provided library.

**Comment by czha5168** [comment]
Hi Johanna, Thanks for your confirmation and suggestions on evaluation settings. I really appreciate it. Wish all the best!

**Comment by czha5168** [comment]
Hi Johanna, I noticed a semantic label as "remove", would you mind leaving some comments on this semantic label, please? I also found a special label_encoding in RIO27 (https://docs.google.com/spreadsheets/d/1eRTJ2M9OHz7ypXfYD-KTR1AIT-CrVLmhJf8mxgVZWnI/edit#gid=0), i.e., its id equals **'0'** and name equals **'-'**. Is it reasonable for us to treat these two semantic annotations equally? Or should we simply ignore the points annotated with "remove" labels?
Thanks!
